var generalConfig = angular.module('GeneralConfig',['pascalprecht.translate']);

generalConfig.config(["$translateProvider","$translatePartialLoaderProvider","$injector","profile",
	function($translateProvider,$translatePartialLoaderProvider,$injector,profile){
		var config = $injector.get(profile);
		$translatePartialLoaderProvider.addPart('main');
		$translateProvider.useLoader('$translatePartialLoader', {
		  urlTemplate: './app/i18n/{part}/translate-{lang}.json'
		});
		$translateProvider.preferredLanguage(config.languageDefault);
		$translateProvider.useSanitizeValueStrategy('escaped');
}]);

generalConfig.constant("profile","localDEV");

generalConfig.constant("generalDEV",{
	"languageDefault":"en",
	"harborRest":{
		"url":"app/moduleHarbor/mocks/harbor.json",
		"params":["name="]
	},
	"vesselRest":{
		"url":"app/moduleResults/mocks/vessel.json",
		"params":{
				"name":"name=",
				"width":"width=",
				"length":"length=",
				"draft":"draft=",
				"latitutde":"latitutde=",
				"longitude":"longitude=",
				"radius":"radius=",
				"width2":"width2=",
				"length2":"length2=",
				"draft2":"draft2="},
		"width":{
			"gte":"",
			"gt":"",
			"lt":"",
			"lte":""
		},
		"length":{
			"gte":"",
			"gt":"",
			"lt":"",
			"lte":""
		},
		"draft":{
			"gte":"",
			"gt":"",
			"lt":"",
			"lte":""
		}
	},
	"httpError":{
		"404":"10404",
		"default":"10003",
		"00000":"00000",
		"vesselEmpty":"10004"
	}
});

generalConfig.constant("localDEV",{
	"languageDefault":"en",
	"harborRest":{
		"url":"http://localhost/testVesselBack-0.0.1-SNAPSHOT/harbors/search/findByNameContaining",
		"params":{
			"name":"name=",
			"page":"page=",
			"size":"size=",
			"sort":"sort="
		}
	},
	"vesselRest":{
		"url":"http://localhost/testVesselBack-0.0.1-SNAPSHOT/vessels/search/findBy",
		"params":{
				"point":"point=",
				"distance":"distance=",
				"width":"width=",
				"widthFrom":"widthFrom=",
				"widthTo":"widthTo=",
				"length":"length=",
				"lengthFrom":"lengthFrom=",
				"lengthTo":"lengthTo=",
				"draft":"draft=",
				"draftFrom":"draftFrom=",
				"draftTo":"draftTo=",
				"name":"name=",
				"page":"page=",
				"size":"size=",
				"sort":"sort="
			},
		"point":"PointNear",
		"name":"NameContaining",
		"width":"Width",
		"length":"Length",
		"draft":"Draft",
		"gte":"GreaterThanEqual",
		"gt":"GreaterThan",
		"lt":"LessThan",
		"lte":"LessThanEqual",
		"btw":"Between",
		"and":"And"
	},
	"vesselRestNew":{
		"url":"http://localhost/testVesselBack-0.0.1-SNAPSHOT/vessels"
	},
	"httpError":{
		"404":"10404",
		"default":"10003",
		"noResults":"00000",
		"vesselEmpty":"10004",
		"OK":"10005"
	}
});